"""
CSRF & IDOR Testing Module
"""
import asyncio
import aiohttp
import re
import os
import sys
from typing import List, Dict, Any, Optional
from urllib.parse import urljoin, urlparse, parse_qs

# Add root to path
root_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if root_dir not in sys.path:
    sys.path.insert(0, root_dir)

from nx_platform.v4.core.config import logger


class CSRFTester:
    """
    Tests for CSRF vulnerabilities by:
    1. Detecting missing CSRF tokens in forms
    2. Generating CSRF PoC HTML
    3. Attempting state-changing operations without tokens
    """
    
    def __init__(self, target: str):
        self.target = target
        self.session: Optional[aiohttp.ClientSession] = None
    
    async def __aenter__(self):
        self.session = aiohttp.ClientSession(
            timeout=aiohttp.ClientTimeout(total=20),
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
        )
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.session:
            await self.session.close()
    
    async def test_csrf_on_form(self, form_info: Dict) -> Optional[Dict]:
        """
        Test CSRF vulnerability on a form
        
        Returns finding if vulnerable, None if not
        """
        url = form_info.get("form_action") or form_info.get("url")
        method = form_info.get("method", "POST").upper()
        
        if not url:
            return None
        
        logger.info(f"[CSRF Test] Testing: {url}")
        
        # Generate CSRF PoC HTML
        csrf_poc = self._generate_csrf_poc(form_info)
        
        # Try to submit form without CSRF token
        try:
            # Get initial state (if possible)
            # Then submit without token
            
            # Prepare form data
            form_data = aiohttp.FormData()
            for inp in form_info.get("inputs", []):
                if inp.get("type") != "submit" and not inp.get("is_csrf_token"):
                    # Use test values
                    if inp.get("is_sensitive"):
                        form_data.add_field(inp["name"], "test")
                    else:
                        form_data.add_field(inp["name"], "test")
            
            # Submit without CSRF token (by excluding it)
            if method == "POST":
                async with self.session.post(url, data=form_data) as resp:
                    # If submission succeeds without token, might be CSRF vulnerable
                    if resp.status in [200, 201, 302, 303]:
                        # Check if action actually succeeded (different from getting error)
                        response_text = await resp.text()
                        
                        # If no error about missing token, likely vulnerable
                        if "token" not in response_text.lower() or "required" not in response_text.lower():
                            return {
                                "type": "csrf",
                                "severity": "medium",
                                "url": url,
                                "method": method,
                                "description": "Form submitted without CSRF token",
                                "csrf_poc": csrf_poc[:500],  # Store truncated PoC
                                "confidence": 0.7,
                                "vulnerable": True
                            }
            
        except Exception as e:
            logger.debug(f"[CSRF Test] Error: {e}")
        
        return None
    
    def _generate_csrf_poc(self, form_info: Dict) -> str:
        """Generate CSRF PoC HTML"""
        action = form_info.get("form_action", "")
        method = form_info.get("method", "POST").lower()
        
        inputs_html = ""
        for inp in form_info.get("inputs", []):
            if inp.get("type") != "submit" and not inp.get("is_csrf_token"):
                inputs_html += f'<input name="{inp["name"]}" value="test">\n'
        
        poc = f"""<!-- CSRF PoC - Auto-generated by Nexusuite AI -->
<html>
<body>
<form action="{action}" method="{method}">
{inputs_html}
</form>
<script>
document.forms[0].submit();
</script>
</body>
</html>"""
        
        return poc


class IDORTester:
    """
    Tests for IDOR (Insecure Direct Object Reference) vulnerabilities
    
    Strategy:
    1. Identify parameters that reference objects (id, user_id, etc.)
    2. Try to access/modify other users' resources
    3. Check for horizontal/vertical privilege escalation
    """
    
    def __init__(self, target: str):
        self.target = target
        self.session: Optional[aiohttp.ClientSession] = None
        
        # IDOR-prone parameter patterns
        self.idor_params = [
            "id", "user_id", "uid", "account_id", "profile_id",
            "order_id", "invoice_id", "transaction_id", "post_id",
            "comment_id", "file_id", "doc_id", "item_id", "product_id",
            "category_id", "group_id", "role_id", "address_id", "member_id"
        ]
    
    async def __aenter__(self):
        self.session = aiohttp.ClientSession(
            timeout=aiohttp.ClientTimeout(total=20),
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
        )
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.session:
            await self.session.close()
    
    async def test_idor(self, candidate: Dict) -> Optional[Dict]:
        """
        Test IDOR vulnerability on a candidate URL
        
        Strategy:
        1. Get initial response with original parameter value
        2. Modify parameter to different value
        3. Compare responses - if similar content, likely IDOR
        """
        url = candidate["url"]
        param = candidate["param"]
        example_value = candidate.get("example_value", "1")
        
        logger.info(f"[IDOR Test] Testing: {url} with param {param}")
        
        try:
            # Test 1: Try different numeric values
            test_values = []
            
            # If current value is numeric, try increment/decrement
            if example_value.isdigit():
                current_num = int(example_value)
                test_values = [str(current_num + 1), str(current_num - 1), str(current_num + 100)]
            else:
                # Try UUID-like or other patterns
                test_values = ["1", "2", "admin", "test", "null"]
            
            # Get baseline response
            async with self.session.get(url) as baseline_resp:
                baseline_content = await baseline_resp.text()
                baseline_status = baseline_resp.status
            
            # Test each value
            for test_value in test_values:
                # Modify parameter
                parsed = urlparse(url)
                params = parse_qs(parsed.query)
                
                # Replace the IDOR-prone parameter
                original_value = params.get(param, [example_value])[0]
                params[param] = [test_value]
                
                # Rebuild URL
                from urllib.parse import urlencode
                test_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}?{urlencode(params, doseq=True)}"
                
                async with self.session.get(test_url) as test_resp:
                    test_content = await test_resp.text()
                    test_status = test_resp.status
                
                # Check for IDOR indicators:
                # 1. Same status code but different content (successful access)
                # 2. 200 status on both with different user data
                # 3. No "unauthorized" or "forbidden" message
                
                if test_status == baseline_status == 200:
                    # Both returned 200 - check if we got different data
                    
                    # Check if we got access to different data
                    # (e.g., different user profile, different order)
                    if test_content != baseline_content:
                        # Check if the new content looks like valid data
                        # (not error page, not login page)
                        if not self._is_error_page(test_content):
                            return {
                                "type": "idor",
                                "severity": "high",
                                "original_url": url,
                                "test_url": test_url,
                                "vulnerable_param": param,
                                "original_value": original_value,
                                "test_value": test_value,
                                "description": f"IDOR detected - accessed data with {param}={test_value}",
                                "evidence": f"Original: {baseline_content[:200]}... | Test: {test_content[:200]}...",
                                "confidence": 0.75,
                                "vulnerable": True
                            }
                
                # Check if we got unauthorized instead
                if test_status == 403 or test_status == 401:
                    # Not vulnerable - proper auth check
                    break
                
                await asyncio.sleep(0.2)
                
        except Exception as e:
            logger.debug(f"[IDOR Test] Error: {e}")
        
        return None
    
    def _is_error_page(self, content: str) -> bool:
        """Check if content is an error/unauthorized page"""
        content_lower = content.lower()
        
        error_patterns = [
            "unauthorized", "forbidden", "access denied",
            "not authorized", "permission denied", "login",
            "sign in", "please login"
        ]
        
        return any(pattern in content_lower for pattern in error_patterns)


async def run_csrf_tests(target: str, csrf_candidates: List[Dict]) -> List[Dict]:
    """Run CSRF tests on all candidates"""
    findings = []
    
    async with CSRFTester(target) as tester:
        for candidate in csrf_candidates:
            result = await tester.test_csrf_on_form(candidate)
            if result:
                findings.append(result)
                logger.info(f"[CSRF] ⚠️ VULNERABLE: {result['description']}")
    
    return findings


async def run_idor_tests(target: str, idor_candidates: List[Dict]) -> List[Dict]:
    """Run IDOR tests on all candidates"""
    findings = []
    
    async with IDORTester(target) as tester:
        for candidate in idor_candidates:
            result = await tester.test_idor(candidate)
            if result:
                findings.append(result)
                logger.info(f"[IDOR] ⚠️ VULNERABLE: {result['description']}")
    
    return findings


async def run_all_form_tests(target: str, form_analysis_results: List[Dict]) -> List[Dict]:
    """
    Run all form-related vulnerability tests:
    - CSRF
    - SQL Injection on login forms
    - IDOR
    """
    all_findings = []
    
    # Extract testable endpoints
    from form_analyzer import extract_testable_endpoints
    endpoints = extract_testable_endpoints(form_analysis_results)
    
    logger.info(f"[Form Tests] Starting tests:")
    logger.info(f"  - CSRF vulnerable forms: {len(endpoints['csrf_vulnerable_forms'])}")
    logger.info(f"  - Login forms: {len(endpoints['login_forms'])}")
    logger.info(f"  - IDOR candidates: {len(endpoints['idor_candidates'])}")
    
    # Run CSRF tests
    if endpoints["csrf_vulnerable_forms"]:
        csrf_findings = await run_csrf_tests(target, endpoints["csrf_vulnerable_forms"])
        all_findings.extend(csrf_findings)
    
    # Run IDOR tests
    if endpoints["idor_candidates"]:
        idor_findings = await run_idor_tests(target, endpoints["idor_candidates"])
        all_findings.extend(idor_findings)
    
    return all_findings