# ==============================================================================
# Automated Vulnerability Auditing & Triage
# ==============================================================================

set +e

gum style --margin "1 0" --foreground 212 "## 🔍 Starting Automated Auditing & Triage..."

export TOTAL_CONFIRMED_BUGS=0
AUDIT_SUMMARY_FILE="$OUTPUT_BASE/audited_summary.txt"
> "$AUDIT_SUMMARY_FILE"

for target_dir in "$OUTPUT_BASE/targets/"*; do
    [[ -d "$target_dir" ]] || continue
    target_name=$(basename "$target_dir")
    
    AUDIT_FILE="$target_dir/vulnerabilities/audited_confirmed.txt"
    > "$AUDIT_FILE"
    
    log_msg ">" "\033[1;36m" "$target_name" "AUDIT" "Verifying raw vulnerability logs..."
    
    # 1. Audit SQLMap: Mencari indikasi injeksi sukses ([CRITICAL] atau adanya file target.txt)
    if [[ -d "$target_dir/vulnerabilities/sqlmap" ]]; then
        find "$target_dir/vulnerabilities/sqlmap" -name "log" -type f 2>/dev/null | while read -r logfile; do
            if grep -q "\[CRITICAL\]" "$logfile" || grep -q "vulnerable" "$logfile"; then
                echo "[SQLi] Confirmed SQL Injection in URL/Parameter found by SQLMap" >> "$AUDIT_FILE"
            fi
        done
        
        # Jika ada file target.txt, itu artinya payload sudah berhasil terinjeksi
        find "$target_dir/vulnerabilities/sqlmap" -name "target.txt" -type f 2>/dev/null | while read -r targetfile; do
            echo "[SQLi] SQL Injection Confirmed. Payload tested successfully." >> "$AUDIT_FILE"
        done
    fi
    
    # 2. Audit Dalfox (XSS): Hanya menyimpan yang benar-benar memiliki status POC (Proof of Concept)
    if [[ -s "$target_dir/vulnerabilities/xss.txt" ]]; then
        if grep -q "POC" "$target_dir/vulnerabilities/xss.txt" || grep -q "Vulnerable" "$target_dir/vulnerabilities/xss.txt"; then
            echo "[XSS] Confirmed Cross-Site Scripting. POC generated by Dalfox." >> "$AUDIT_FILE"
        fi
    fi
    
    # 3. Audit Nuclei: Menyaring hanya temuan [critical] dan [high] untuk mengabaikan false-positive/informational
    if [[ -s "$target_dir/vulnerabilities/nuclei.txt" ]]; then
        grep -iE '\[(high|critical)\]' "$target_dir/vulnerabilities/nuclei.txt" | while read -r line; do
            echo "[Nuclei] Confirmed High/Critical: $line" >> "$AUDIT_FILE"
        done
    fi
    
    # 4. Audit Wapiti: Mencari kata kunci Vulnerability yang valid (bukan sekedar info)
    for wfile in "$target_dir/vulnerabilities"/wapiti_*.txt; do
        [[ -f "$wfile" ]] || continue
        if grep -qi "Vulnerability found" "$wfile" || grep -qi "\[+\]" "$wfile"; then
            echo "[Wapiti] Potential Injection confirmed in Wapiti logs" >> "$AUDIT_FILE"
        fi
    done
    
    # 5. Audit FFUF: Memeriksa direktori/file penting yang ditemukan (Status 200 OK)
    for ffile in "$target_dir/recon"/ffuf_*.json; do
        [[ -f "$ffile" ]] || continue
        # Menggunakan jq untuk mencari endpoint dengan status 200
        jq -r '.results[] | select(.status == 200) | .url' "$ffile" 2>/dev/null | grep -iE '(admin|config|backup|api|secret|login|db|sql|env|\.git|\.bak|\.old|\.zip|\.tar)' | while read -r sensitive_url; do
            echo "[FFUF] Confirmed Exposed Sensitive Path: $sensitive_url" >> "$AUDIT_FILE"
        done
    done

    # 6. Audit NMAP: Mengekstrak CVE, Exploit, dan skor kerentanan
    if [[ -f "$target_dir/scans/nmap.nmap" ]]; then
        # Menggunakan grep dengan regex yang lebih longgar untuk menangkap CVE dan vulners
        grep -iE "VULNERABLE|EXPLOIT|vulners:|CVE-[0-9]{4}-[0-9]+" "$target_dir/scans/nmap.nmap" | while read -r nmap_vuln; do
            # Bersihkan output (hapus karakter | dan spasi berlebih di awal)
            clean_vuln=$(echo "$nmap_vuln" | sed 's/^[|[:space:]]*//')
            echo "[Nmap] Vulnerability Detected: $clean_vuln" >> "$AUDIT_FILE"
        done
    fi

    # Menghitung hasil dan merapikan output
    if [[ -s "$AUDIT_FILE" ]]; then
        # Buang duplikat log (sort -u) jika tools mendeteksi hal yang sama berkali-kali
        sort -u -o "$AUDIT_FILE" "$AUDIT_FILE"
        bug_count=$(wc -l < "$AUDIT_FILE")
        
        log_msg "✓" "\033[1;32m" "$target_name" "AUDIT" "Found $bug_count confirmed vulnerabilities!"
        
        echo "--- $target_name ---" >> "$AUDIT_SUMMARY_FILE"
        cat "$AUDIT_FILE" >> "$AUDIT_SUMMARY_FILE"
        echo "" >> "$AUDIT_SUMMARY_FILE"
        
        ((TOTAL_CONFIRMED_BUGS += bug_count))
    else
        log_msg "✓" "\033[1;32m" "$target_name" "AUDIT" "Clean. No critical bugs confirmed."
        rm -f "$AUDIT_FILE"
    fi
done

if [[ $TOTAL_CONFIRMED_BUGS -gt 0 ]]; then
    gum style --foreground 46 --border normal --border-foreground 46 --padding "0 2" "🎯 Automated Auditing Complete! $TOTAL_CONFIRMED_BUGS valid bugs confirmed."
else
    gum style --foreground 240 --border normal --border-foreground 240 --padding "0 2" "🛡️ Automated Auditing Complete! No high/critical bugs passed verification."
fi
